using System.Collections.Generic;
using UnityEngine;

public static class SMBHUtils {
	public static readonly Dictionary<Color, string> NameOfColor = new Dictionary<Color, string> {
		{ (Color)new Color32(0xff, 0x80, 0, 0), "Orange" },
		{ Color.white, "White" },
		{ Color.red, "Red" },
		{ Color.yellow, "Yellow" },
		{ Color.green, "Green" },
		{ Color.blue, "Blue" },
	};

	public static readonly string[] DefaultIgnoredModules = new[] {
		"+",
		"14",
		"42",
		"501",
		"A>N<D",
		"Amnesia",
		"B-Machine",
		"Bamboozling Time Keeper",
		"Black Arrows",
		"Brainf---",
		"Busy Beaver",
		"Button Messer",
		"Concentration",
		"Cookie Jars",
		"Cube Synchronization",
		"Divided Squares",
		"Don't Touch Anything",
		"Doomsday Button",
		"Duck Konundrum",
		"Encryption Bingo",
		"Floor Lights",
		"Forget Any Color",
		"Forget Enigma",
		"Forget Everything",
		"Forget Infinity",
		"Forget It Not",
		"Forget Maze Not",
		"Forget Me Later",
		"Forget Me Not",
		"Forget Perspective",
		"Forget The Colors",
		"Forget Them All",
		"Forget This",
		"Forget Us Not",
		"Four-Card Monte",
		"Gemory",
		"Hogwarts",
		"Iconic",
		"Keypad Directionality",
		"Kugelblitz",
		"Multitask",
		"Mystery Module",
		"OmegaDestroyer",
		"OmegaForget",
		"Organization",
		"Out of Time",
		"Password Destroyer",
		"Pow",
		"Purgatory",
		"RPS Judging",
		"SMBH",
		"Scrabble Scramble",
		"Security Council",
		"Shoddy Chess",
		"Simon",
		"Simon Forgets",
		"Simon's Stages",
		"Soulscream",
		"Souvenir",
		"Tallordered Keys",
		"Tetrahedron",
		"The Board Walk",
		"The Heart",
		"The Klaxon",
		"The Swan",
		"The Time Keeper",
		"The Troll",
		"The Twin",
		"The Very Annoying Button",
		"Timing is Everything",
		"Turn The Key",
		"Turn The Keys",
		"Ultimate Custom Night",
		"Whiteout",
		"Zener Cards",
		"Übermodule",
	};
}
